language: java
sudo: false # faster builds
jdk:
  - openjdk12
  - openjdk13
  - openjdk14
script: mvn clean verify
services: - mysql
spring:
datasource: 
url: jdbc:mysql://localhost:3306/cityzendb?serverTimezone=UTC
username: root
password: admin
