language: java
sudo: true # faster builds
jdk:
  - openjdk12
  - openjdk13
  - openjdk14
script: mvn clean verify
services:
  - mysql
before_install:
  - sudo service mysql stop
  - sudo mysqld --init-file= test/mysql-init.txt
  - sudo service mysql start
  - mysql -u root --password="admin" < test/travis.sql


