language: java
sudo: false # faster builds
jdk:
  - openjdk12
  - openjdk13
  - openjdk14
script: mvn clean verify
services:
  - mysql
before_install:
  - mysql -u dev --password="" < test/travis.sql


