language: java
sudo: false # faster builds
jdk:
  - openjdk12
  - openjdk13
  - openjdk14
script: mvn clean verify
services:
  - mysql
before_install:
  - mysqld --init-file=test/mysql-init.txt
  - mysql -u root --password="admin" < test/travis.sql


